### ISSUE TITLE
Multi select with material design look'n feel

### ISSUE THREAD

**Issue by sebschaeffler** [sebschaeffler/iris-react#3]
Material design does not provide a dropdown with multiple selection.
While it might be considered as an anti-pattern and other solutions exist, e.g. pick lists, table etc.. it's still convenient to have this component in the toolbox especially because it takes much less space on the screen...

**Comment by bidispot** [comment]
I created a multi select component based on material-ui "SelectField" and "DropDownMenu "by adding checkboxes within the dropdown. The the dropdown will iterate on the selected values to concatenate the result as the new label.

**Comment by bidispot** [comment]
There are still 2 pending issues:
- Styling issue: Even though there is no values in the create page it seems the component already displayed an empty string leading to a UI glitch
- (de)selecting a value in the dropdown should trigger a change in redux-form implying the form is not pristine anymore
